@startuml

skinparam class {
    FontName Arial
    BorderColor black
    BackgroundColor whitesmoke
    ArrowColor black
}

title ClusterEmulator.Emulation Class Diagram


namespace Controllers {
    class AdaptableController {
        - engine : IEngine
        - log : ILogger<AdaptableController>
        - correlatedLog : IScopedLogContextFactory
        - ProcessRequestAsync(name, caller) : IActionResult
        + Get(name, caller) : IActionResult
        + Delete(name, caller) : IActionResult
        + Options(name, caller) : IActionResult
        + Post(name, request, caller) : IActionResult
        + Put(name, request, caller) : IActionResult
    }
}

namespace Core {
    interface IConfigFactory<TModel> {
        + Create(settingValue) : TModel
    }

    class ConfigFactory<TModel> implements IConfigFactory {
        - serializerSettings : JsonSerializerSettings
        # log : ILogger
        # Errors : List<string>
        ..getters..
        # SerializerSettings : JsonSerializerSettings
        ----
        # DeserializeSettingWithErrorHandling(settingValue) : TModel
        + ConfigFactory(ILogger logger)
    }

    interface IEngine {
        + ProcessRequestAsync(name) : IActionResult
        + ProcessStartupActionsAsync()
    }

    class Engine implements IEngine {
        - registry : IRegistry
        - log : ILogger
        - RunStartupSteps(steps, processorName)
        - ExcuteStepInParallel(name, stepName, step) : ExecutionStatus
        + Engine(logger, registry)
    }

    interface IConfigModel<TModel> {
        + AsTypeModel(logger) : TModel
    }

    interface IRegistry {
        + PolicyRegistry : IPolicyRegistry<string>
        + Clients : IEnumerable<KeyValuePair<string, ClientConfig>>
        + ConfigureHttpClients(httpClientFactory)
        + GetClient(name) : ClientConfig
        + GetPolicy(name) : IAsyncPolicy<HttpResponseMessage>
        + GetRequestProcessor(name) : IRequestProcessor
        + GetStartupProcessors() : IEnumerable<IStartupProcessor>
        + GetStep(name) : IStep
    }

    interface IRegistrySettings {
        + TryGetSection(name, out section) : bool
    }

    class Registry implements IRegistry {
        - clients : IDictionary<string, ClientConfig>
        - policies : IDictionary<string, IAsyncPolicy<HttpResponseMessage>>
        - processors : IDictionary<string, IProcessor>
        - steps : IDictionary<string, IStep>
        - log : ILogger
        - simpleClientFactory : IHttpClientFactory
        + {static} ClientsSection : string
        + {static} PoliciesSection : string
        + {static} ProcessorsSection : string
        + {static} StepsSection : string
        ..getters..
        + Clients : IEnumerable<KeyValuePair<string, ClientConfig>>
        + PolicyRegistry : IPolicyRegistry<string>
        ----
        - InitializeFromSettings<T>(settings, sectionName, registry, factory);
        - GetRegisteredValue<T>(name, registry, registryName) : T
        + Registry(settings, stepFactory, processorFactory, policyFactory,
        clientFactory, logger, loggerFactory)
        + ConfigureHttpClients(httpClientFactory)
    }

    class NestedConfigFactory<TConfigModel, TModel> extends ConfigFactory {
        - logFactory : ILoggerFactory
        - configNamespace : string
        + NestedConfigFactory(logger, loggerFactory)        
    }

    class SimpleHttpClientFactory implements System.Net.Http.IHttpClientFactory {
        - clients : IDictionary<string, ClientConfig>
        - log : ILogger
        + SimpleHttpClientFactory(clientConfigs, logger)
    }
}


namespace Extensions {
    class ServiceCollectionExtensions << (S,#DDAA00) static >> {
        + {static} AddSimulationEngine(serviceCollection) : IServiceCollection
        + {static} AddSimulationEngineClients(serviceCollection, registry)
    }
}


namespace System.Net.Http {
    interface IHttpClientFactory {
        + CreateClient(name) : HttpClient
    }

    IHttpClientFactory --> HttpClient : creates >
}

namespace HttpClientConfiguration {
    interface IPolicyConfiguration<extends IConfigModel<IAsyncPolicy>> extends Core.IConfigModel

    class PolicyExtensions << (S,#DDAA00) static >> {
        + {static} HandleHttpRequests() : PolicyBuilder<HttpResponseMessage>
    }

    class AdvancedCircuitBreakerConfig implements IPolicyConfiguration {
        + BreakDuration : double
        + FailureThreshold : double
        + SamplingDuration : double
        + MinimumThroughput : integer
    }

    class BulkheadConfig implements IPolicyConfiguration {
        + MaxParallelization : integer
        + MaxQueuingActions : integer
    }

    class CacheConfig implements IPolicyConfiguration {
        + Time : CacheTime
        + Absolute : boolean
        + Sliding : boolean
        - cacheProvider : IAsyncCacheProvider
        - strategy : ITtlStrategy
        + CacheConfig()
        + CacheConfig(cacheProvider)
        - CacheOKResponse(pollyContext, httpResponseMessage) : Ttl
        - CreateStrategy() : ITtlStrategy
    }

    class CacheTime {
        + Days : integer
        + Hours : integer
        + Minutes : integer
        + Seconds : integer
        + AsTimeSpan() : TimeSpan
    }

    class CircuitBreakerConfig implements IPolicyConfiguration {
        + BreakDuration : double
        + FaultTolerance : integer        
    }

    class FallbackConfig implements IPolicyConfiguration { 
        + Content : string
        + Reason : string
        + Status : integer        
    }

    class RetryConfig implements IPolicyConfiguration {
        + Retries : integer
        + DelaysInSeconds : IEnumerable<double>
        + JitterMilliseconds : integer
        - Delay(retryCount, exponential) : TimeSpan
        - ExponentialDelay(retryCount) : TimeSpan
        - DelayWithJitter(delay) : TimeSpan
    }

    class TimeoutConfig implements IPolicyConfiguration {
        + CancelDelegates : boolean
        + TimeoutInSeconds : double
    }

    class ClientConfig {
        + BaseAddress : string
        + Policies : IEnumerable<string>
        + RequestHeaders : IDictionary<string, string>
    }
}

namespace Logging {
    interface IScopedLogContextFactory {
        + InitializeFrom(httpContext) : IDisposable
    }
}

namespace Processors {
    interface IProcessor<extends IConfigModel<IProcessor>> extends Core.IConfigModel {
        + Steps : IList<string>
    }

    interface IRequestProcessor extends IProcessor {        
        + ErrorPayload : ErrorResponse
        + ErrorPayloadSize : integer
        + IngressLatencyMilliseconds : integer
        + SuccessPayload : SuccessResponse
        + SuccessPayloadSize : integer
    }

    interface IStartupProcessor extends IProcessor {
        + Asynchronous : boolean
    }

    abstract Processor implements IProcessor {
        # Log : ILogger
    }

    class RequestProcessor extends Processor implements IRequestProcessor

    class StartupProcessor extends Processor implements IStartupProcessor
}

namespace Steps {
    interface IStep<extends IConfigModel<IStep>> extends Core.IConfigModel {
        + ParallelCount : uint
        + FailOnParallelFailures : GroupClause
        + ExecuteAsync() : ExecutionStatus
    }

    enum GroupClause {
        + Undefined
        + Any
        + All
        + None
    }

    enum ExecutionStatus {
        + Fail
        + Success
        + SimulatedFail
    }

    interface IRequestStep extends IStep {
        + ClientName : string
        + ReuseHttpMessageHandler : boolean
        + Configure(httpClientFactory)
        + Configure(httpClientFactory, requestPolicy);
    }

    abstract SimulationStep implements IStep {
        # Logger : ILogger
        + {abstract} ExecuteAsync : ExecutionStatus
    }

    class DelayStep implements SimulationStep {
        + Time : double
        - Delay : TimeSpan
    }

    class ErrorStep implements SimulationStep {
        + Probability : double
    }

    class LoadStep implements SimulationStep {
        + TimeInSeconds : double
        + CpuPercentage : integer
        + MaxProcessors : integer
        + MemoryInBytes : ulong
        - ProcessorCount : integer
        - GenerateLoad(seconds, percentage)
    }

    class RequestStep implements SimulationStep, IRequestStep {
        - {static} ChunkChars : integer
        - configured : boolean
        - policy : IAsyncPolicy
        - clientFactory : IHttpClientFactory
        - random : Random
        - pendingDisposals : IDictionary<Guid, IList<IDisposable>>
        - supportedMethodNames : ISet<string>
        - supportedMethods : ISet<HttpMethod>
        + Asynchrounous : boolean
        + CacheId : string
        + CacheUniqueness : integer
        + Method : string
        + Path : string
        + PayloadSize : string
        .. getters ..
        - {static} httpMethods : IEnumerable<HttpMethod>
        - Context : Polly.Context
        - CacheKeyNumber : integer
        + Configured : configured
        ----
        - DisposePending(disposalKey)
        - ExecuteRequestAsync(action, cancellationToken) : HttpResponseMessage
        - GenerateRequest() : AdaptableRequest
        - GetRequestAction(httpClient, disposalId) : Func<CancellationToken, Task<HttpResponseMessage>>
        - HandleRequestAsync(request, disposalId)
        - ScheduleDisposal(disposalKey, disposable)
        - SendRequest(requestTask)
    }
}

Controllers.AdaptableController o--> Core.IEngine : ProcessRequestAsync(name) >
Controllers.AdaptableController o--> Logging.IScopedLogContextFactory : InitializeFrom(httpContext)

Core.Engine o--> Core.IRegistry : GetStep(name)\nGetStartupProcessors()\nGetRequestProcessor(name) >
Core.Engine --> Processors.IRequestProcessor
Core.Engine --> Processors.IStartupProcessor
Core.Engine --> Steps.IStep : ExecuteAsync()

Core.NestedConfigFactory --> Core.IConfigModel : AsTypeModel(logger)\nTConfigModel implements >

Core.Registry o--> "0..*" HttpClientConfiguration.ClientConfig
Core.Registry o--> "1..*" Processors.IProcessor
Core.Registry o--> "1..*" Steps.IStep

Core.Registry o--> Polly.PolicyRegistry
Core.Registry o--> "0..*" Polly.IAsyncPolicy
Core.Registry o--> System.Net.Http.IHttpClientFactory

Core.Registry --> Core.IRegistrySettings : TryGetSection(name, out section) >
Core.Registry --> Core.IConfigFactory : Create(settingValue)\nTModel:\n1. <IStep>\n2. <IProcessor>\n3. <IAsyncPolicy>\n4. <ClientConfig> >
Core.Registry --> Core.SimpleHttpClientFactory : new(clients, logger) >
Core.Registry --> Polly.PolicyRegistry : Add(policyKey, policy)
Core.Registry --> Steps.IRequestStep : Configure(httpClientFactory),\nConfigure(httpClientFactory, requestPolicy)  >

Core.SimpleHttpClientFactory o--> "0..*" HttpClientConfiguration.ClientConfig

Microsoft.Extensions.DependencyInjection.IServiceCollection <-- Extensions.ServiceCollectionExtensions : < extends
Extensions.ServiceCollectionExtensions --> Core.IConfigFactory : registers IAsyncPolicy factory type\nregisters IStep factory type\nregisters IProcessor factory type\nregisters ClientConfig factory type >
Extensions.ServiceCollectionExtensions --> Core.NestedConfigFactory : registers IAsyncPolicy factory implementation\nregisters IStep factory implementation\nregisters IProcessor factory implementation >
Extensions.ServiceCollectionExtensions --> Core.ConfigFactory : registers ClientConfig factory type >
Extensions.ServiceCollectionExtensions --> Core.IRegistry : registers type >
Extensions.ServiceCollectionExtensions --> Core.Registry : registers implementation of IRegistry >
Extensions.ServiceCollectionExtensions --> Core.IEngine : registers type >
Extensions.ServiceCollectionExtensions --> Core.Engine : registers implementation of IEngine >

HttpClientConfiguration.IPolicyConfiguration --> Polly.IAsyncPolicy : creates >

HttpClientConfiguration.AdvancedCircuitBreakerConfig --> HttpClientConfiguration.PolicyExtensions : HandleHttpRequests()
HttpClientConfiguration.AdvancedCircuitBreakerConfig --> Polly.AsyncAdvancedCircuitBreakerTResultSyntax : AdvancedCircuitBreakerAsync()

HttpClientConfiguration.BulkheadConfig --> Polly.Policy : BulkheadAsync() >

HttpClientConfiguration.CacheConfig *--> HttpClientConfiguration.CacheTime
HttpClientConfiguration.CacheConfig o--> Polly.Caching.IAsyncCacheProvider
HttpClientConfiguration.CacheConfig o--> Polly.Caching.ITtlStrategy
HttpClientConfiguration.CacheConfig --> Polly.Caching.AbsoluteTtl : new() >
HttpClientConfiguration.CacheConfig --> Polly.Caching.SlidingTtl : new() >
HttpClientConfiguration.CacheConfig --> Polly.Caching.RelativeTtl : new() >
HttpClientConfiguration.CacheConfig --> Polly.Caching.ResultTtl : new() >
HttpClientConfiguration.CacheConfig --> Polly.Policy : CacheAsync() >
HttpClientConfiguration.CacheConfig --> Microsoft.Extensions.Caching.Memory.IMemoryCache : new() >

HttpClientConfiguration.CircuitBreakerConfig --> HttpClientConfiguration.PolicyExtensions : HandleHttpRequests() >
HttpClientConfiguration.CircuitBreakerConfig --> Polly.AsyncCircuitBreakerTResultSyntax : CircuitBreakerAsync()

HttpClientConfiguration.FallbackConfig --> HttpClientConfiguration.PolicyExtensions : HandleHttpRequests() >
HttpClientConfiguration.FallbackConfig --> Polly.AsyncFallbackTResultSyntax : FallbackAsync() >

HttpClientConfiguration.PolicyExtensions --> Polly.Policy : Handle<HttpRequestException>() >
HttpClientConfiguration.PolicyExtensions --> Polly.PolicyBuilder : Or<TimeoutRejectedException>()\n.OrResult<HttpResponseMessage>(errorMessage) >

HttpClientConfiguration.RetryConfig --> HttpClientConfiguration.PolicyExtensions : HandleHttpRequests() >
HttpClientConfiguration.RetryConfig --> Polly.PolicyBuilder : RetryForeverAsync()\nRetryAsync()\nWaitAndRetryForeverAsync()\nWaitAndRetryAsync() >

HttpClientConfiguration.TimeoutConfig --> Polly.Policy : TimeoutAsync() >

Processors.RequestProcessor *--> ClusterEmulator.Models.ErrorResponse
Processors.RequestProcessor *--> ClusterEmulator.Models.SuccessResponse

Steps.GroupClause <--* Steps.SimulationStep
Steps.ExecutionStatus <-- Steps.SimulationStep
Steps.IStep <-- Steps.SimulationStep : creates <

Steps.RequestStep o--> Polly.Context : new() >
Steps.RequestStep o--> System.Net.Http.IHttpClientFactory : CreateClient(name) >
Steps.RequestStep --> Polly.IAsyncPolicy : ExecuteAsync() >

Steps.RequestStep --> System.Net.Http.HttpClient : DefaultRequestHeaders.Add()\nSendAsync(request, cancellationToken) >

Steps.RequestStep --> ClusterEmulator.Models.AdaptableRequest : create


@enduml