@startuml

skinparam class {
    FontName Arial
    BorderColor black
    BackgroundColor whitesmoke
    ArrowColor black
}

title ClusterEmulator.Emulation Core Class Diagram

namespace ClusterEmulator.Emulation.Controllers {
    class AdaptableController {
        - engine : IEngine
        - log : ILogger<AdaptableController>
        - correlatedLog : IScopedLogContextFactory
        - ProcessRequestAsync(name, caller) : IActionResult
        + Get(name, caller) : IActionResult
        + Delete(name, caller) : IActionResult
        + Options(name, caller) : IActionResult
        + Post(name, request, caller) : IActionResult
        + Put(name, request, caller) : IActionResult
    }
}

namespace ClusterEmulator.Emulation.Core {
    interface IConfigFactory<TModel> {
        + Create(settingValue) : TModel
    }

    class ConfigFactory<TModel> implements IConfigFactory {
        - serializerSettings : JsonSerializerSettings
        # log : ILogger
        # Errors : List<string>
        ..getters..
        # SerializerSettings : JsonSerializerSettings
        ----
        # DeserializeSettingWithErrorHandling(settingValue) : TModel
        + ConfigFactory(ILogger logger)
    }

    interface IEngine {
        + ProcessRequestAsync(name) : IActionResult
        + ProcessStartupActionsAsync()
    }

    class Engine implements IEngine {
        - registry : IRegistry
        - log : ILogger
        - RunStartupSteps(steps, processorName)
        - ExcuteStepInParallel(name, stepName, step) : ExecutionStatus
        + Engine(logger, registry)
    }

    interface IConfigModel<TModel> {
        + AsTypeModel(logger) : TModel
    }

    interface IRegistry {
        + PolicyRegistry : IPolicyRegistry<string>
        + Clients : IEnumerable<KeyValuePair<string, ClientConfig>>
        + ConfigureHttpClients(httpClientFactory)
        + GetClient(name) : ClientConfig
        + GetPolicy(name) : IAsyncPolicy<HttpResponseMessage>
        + GetRequestProcessor(name) : IRequestProcessor
        + GetStartupProcessors() : IEnumerable<IStartupProcessor>
        + GetStep(name) : IStep
    }

    interface IRegistrySettings {
        + TryGetSection(name, out section) : bool
    }

    class Registry implements IRegistry {
        - clients : IDictionary<string, ClientConfig>
        - policies : IDictionary<string, IAsyncPolicy<HttpResponseMessage>>
        - processors : IDictionary<string, IProcessor>
        - steps : IDictionary<string, IStep>
        - log : ILogger
        - simpleClientFactory : IHttpClientFactory
        + {static} ClientsSection : string
        + {static} PoliciesSection : string
        + {static} ProcessorsSection : string
        + {static} StepsSection : string
        ..getters..
        + Clients : IEnumerable<KeyValuePair<string, ClientConfig>>
        + PolicyRegistry : IPolicyRegistry<string>
        ----
        - InitializeFromSettings<T>(settings, sectionName, registry, factory);
        - GetRegisteredValue<T>(name, registry, registryName) : T
        + Registry(settings, stepFactory, processorFactory, policyFactory,
        clientFactory, logger, loggerFactory)
        + ConfigureHttpClients(httpClientFactory)
    }

    class NestedConfigFactory<TConfigModel, TModel> extends ConfigFactory {
        - logFactory : ILoggerFactory
        - configNamespace : string
        + NestedConfigFactory(logger, loggerFactory)
    }

    class SimpleHttpClientFactory implements System.Net.Http.IHttpClientFactory {
        - clients : IDictionary<string, ClientConfig>
        - log : ILogger
        + SimpleHttpClientFactory(clientConfigs, logger)
    }

    Engine o-> IRegistry
    NestedConfigFactory --> IConfigModel : TConfigModel implements
    NestedConfigFactory -[hidden]> ConfigFactory
    Registry -> IRegistrySettings
    Registry --> IConfigFactory : Create(settingValue)\nTModel:\n1. <IStep>\n2. <IProcessor>\n3. <IAsyncPolicy>\n4. <ClientConfig> >
    Registry --> SimpleHttpClientFactory
}


namespace ClusterEmulator.Emulation.Extensions {
    class ServiceCollectionExtensions << (S,#DDAA00) static >> {
        + {static} AddSimulationEngine(serviceCollection) : IServiceCollection
        + {static} AddSimulationEngineClients(serviceCollection, registry)
    }
}


namespace System.Net.Http #whitesmoke {
    interface IHttpClientFactory {
        + CreateClient(name) : HttpClient
    }
}

namespace ClusterEmulator.Emulation.HttpClientConfiguration {
    interface IPolicyConfiguration<extends IConfigModel<IAsyncPolicy>> extends ClusterEmulator.Emulation.Core.IConfigModel

    class ClientConfig {
        + BaseAddress : string
        + Policies : IEnumerable<string>
        + RequestHeaders : IDictionary<string, string>
    }
}

namespace ClusterEmulator.Emulation.Logging {
    interface IScopedLogContextFactory {
        + InitializeFrom(httpContext) : IDisposable
    }
}

namespace ClusterEmulator.Emulation.Processors {
    interface IProcessor<extends IConfigModel<IProcessor>> extends ClusterEmulator.Emulation.Core.IConfigModel {
        + ClusterEmulator.Emulation.Steps : IList<string>
    }

    interface IRequestProcessor extends IProcessor {
        + ErrorPayload : ErrorResponse
        + ErrorPayloadSize : integer
        + IngressLatencyMilliseconds : integer
        + SuccessPayload : SuccessResponse
        + SuccessPayloadSize : integer
    }

    interface IStartupProcessor extends IProcessor {
        + Asynchronous : boolean
    }
}


namespace ClusterEmulator.Emulation.Steps {
    interface IStep<extends IConfigModel<IStep>> extends ClusterEmulator.Emulation.Core.IConfigModel {
        + ParallelCount : uint
        + FailOnParallelFailures : GroupClause
        + ExecuteAsync() : ExecutionStatus
    }

    interface IRequestStep extends IStep {
        + ClientName : string
        + ReuseHttpMessageHandler : boolean
        + Configure(httpClientFactory)
        + Configure(httpClientFactory, requestPolicy);
    }

    enum GroupClause
    enum ExecutionStatus
}


'Microsoft namespaces'
namespace Microsoft #whitesmoke {
    namespace AspNetCore {
        namespace Mvc {
            interface IActionResult
            class ProducesAttribute
        }
    }

    namespace Extensions {
        namespace DependencyInjection {
            interface IServiceCollection
        }
    }    
}

'Newtonsoft namespaces'
namespace Newtonsoft.Json #whitesmoke {
    class JsonConvert << (S,#DDAA00) static >>
    class JsonSerializer
    class JsonSerializerSettings

    namespace Linq {
        class JObject
    }    
}

'Polly namespaces'
namespace Polly #whitesmoke {
    interface IAsyncPolicy
    class PolicyRegistry
}

'ClusterEmulator.Emulation.Controllers connections'
ClusterEmulator.Emulation.Controllers.AdaptableController o--> ClusterEmulator.Emulation.Core.IEngine
ClusterEmulator.Emulation.Controllers.AdaptableController o-> ClusterEmulator.Emulation.Logging.IScopedLogContextFactory
ClusterEmulator.Emulation.Controllers.AdaptableController -> Microsoft.AspNetCore.Mvc.IActionResult
ClusterEmulator.Emulation.Controllers.AdaptableController -> Microsoft.AspNetCore.Mvc.ProducesAttribute

'ClusterEmulator.Emulation.Core connections'
ClusterEmulator.Emulation.Core.Engine --> ClusterEmulator.Emulation.Processors.IRequestProcessor
ClusterEmulator.Emulation.Core.Engine --> ClusterEmulator.Emulation.Processors.IStartupProcessor
ClusterEmulator.Emulation.Core.Engine --> ClusterEmulator.Emulation.Steps.IStep
ClusterEmulator.Emulation.Core.Engine --> ClusterEmulator.Emulation.Steps.ExecutionStatus
ClusterEmulator.Emulation.Core.Engine --> ClusterEmulator.Emulation.Steps.GroupClause
ClusterEmulator.Emulation.Core.Engine -up-> Microsoft.AspNetCore.Mvc.IActionResult

ClusterEmulator.Emulation.Core.Registry o--> "0..*" ClusterEmulator.Emulation.HttpClientConfiguration.ClientConfig
ClusterEmulator.Emulation.Core.Registry o--> "1..*" ClusterEmulator.Emulation.Processors.IProcessor
ClusterEmulator.Emulation.Core.Registry o--> "1..*" ClusterEmulator.Emulation.Steps.IStep

ClusterEmulator.Emulation.Core.Registry o--> Polly.PolicyRegistry
ClusterEmulator.Emulation.Core.Registry o--> "0..*" Polly.IAsyncPolicy
ClusterEmulator.Emulation.Core.Registry o--> System.Net.Http.IHttpClientFactory

ClusterEmulator.Emulation.Core.Registry --> ClusterEmulator.Emulation.Steps.IRequestStep

ClusterEmulator.Emulation.Core.SimpleHttpClientFactory o--> "0..*" ClusterEmulator.Emulation.HttpClientConfiguration.ClientConfig

ClusterEmulator.Emulation.Core.ConfigFactory o-> Newtonsoft.Json.JsonSerializerSettings
ClusterEmulator.Emulation.Core.ConfigFactory -> Newtonsoft.Json.JsonConvert

ClusterEmulator.Emulation.Core.NestedConfigFactory -> Newtonsoft.Json.JsonSerializer
ClusterEmulator.Emulation.Core.NestedConfigFactory -> Newtonsoft.Json.Linq.JObject


ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions -up-> Microsoft.Extensions.DependencyInjection.IServiceCollection: extends
ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions .[#888888].> ClusterEmulator.Emulation.Core.IConfigFactory : registers IAsyncPolicy, IStep, IProcessor\n& ClientConfig factory types
ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions .[#888888].> ClusterEmulator.Emulation.Core.NestedConfigFactory : registers IAsyncPolicy, IStep &\nIProcessor factory implementations
ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions .[#888888].> ClusterEmulator.Emulation.Core.ConfigFactory : registers ClientConfig factory implementation
ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions .[#888888].> ClusterEmulator.Emulation.Core.IRegistry : registers type
ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions .[#888888].> ClusterEmulator.Emulation.Core.Registry : registers implementation of IRegistry
ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions .[#888888]> ClusterEmulator.Emulation.Core.IEngine : registers type
ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions .[#888888].> ClusterEmulator.Emulation.Core.Engine : registers implementation of IEngine

@enduml