@startuml

title ClusterEmulator.ServiceFabric Class Diagram

skinparam class {
    FontName Arial
    BorderColor black
    BackgroundColor whitesmoke
    ArrowColor black
}

namespace EmulationService {
    namespace Controllers {
        class EmulationController
    }

    namespace Telemetry {
        class CorrelatedLogContext
    }

    class EmulationService {
        - Log : Serilog.ILogger
        # CreateServiceInstanceListeners() : IEnumerable<ServiceInstanceListener>
    }

    class Program << (S,#DDAA00) static >> {
        - ServiceTypeName : string
        {static} - Configuration : IConfiguration
        {static} - Main()
    }

    class Startup {
        - Registry : IRegistry
        + ConfigureServices(serviceCollection)
        + Configure(applicationBuilder, hostingEnvironment,\n       httpClientFactory, emulationRegistry, emulationEngine)
    }

    Startup --> EmulationService

    'Startup -> EmulationService.Telemetry.CorrelatedLogContext'
}

namespace ClusterEmulator.ServiceFabric #whitesmoke {
    namespace Extensions {
        class ServiceCollectionExtensions << (S,#DDAA00) static >>
    }

    namespace Telemetry {
        class StatelessServiceEnricher
    }
}

namespace System.Fabric #whitesmoke {
    class StatelessServiceContext
}

namespace Serilog #whitesmoke {
    namespace Core {
        class Logger
    }

    namespace Context {
        class LogContext << (S,#DDAA00) static >>
    }

    namespace Configuration {
        class LoggerSettingsConfiguration
    }

    interface ILogger
    class SerilogWebHostBuilderExtensions << (S,#DDAA00) static >>
    class ConfigurationLoggerConfigurationExtensions << (S,#DDAA00) static >>
    class LoggerConfiguration
    class Log << (S,#DDAA00) static >>
}

namespace ClusterEmulator.Emulation #whitesmoke {
    namespace Core {
        interface IEngine
        interface IRegistry
    }

    namespace Controllers {
        class AdaptableController
    }

    namespace Logging {
        interface IScopedLogContextFactory
    }

    namespace Extensions {
        class ServiceCollectionExtensions << (S,#DDAA00) static >>
    }
}

namespace Microsoft #whitesmoke {
    namespace Extensions {
        namespace DependencyInjection {
            interface IServiceCollection
            class ServiceCollectionServiceExtensions << (S,#DDAA00) static >>
            class HttpClientFactoryServiceCollectionExtensions << (S,#DDAA00) static >>
            class MvcServiceCollectionExtensions << (S,#DDAA00) static >>
            class MvcCoreMvcBuilderExtensions << (S,#DDAA00) static >>
            class HealthCheckServiceCollectionExtensions << (S,#DDAA00) static >>
        }
        
        namespace Configuration {
            interface IConfiguration
            class ConfigurationBuilder
            class FileConfigurationExtensions << (S,#DDAA00) static >>
            class JsonConfigurationExtensions << (S,#DDAA00) static >>
            class EnvironmentVariablesExtensions << (S,#DDAA00) static >>
        }

        namespace Primitives {
            class StringValues
        }
    }

    namespace AspNetCore {
        namespace Hosting {
            class WebHostBuilder
            class WebHostBuilderExtensions << (S,#DDAA00) static >>
            class WebHostBuilderKestrelExtensions << (S,#DDAA00) static >>
            class HostingAbstractionsWebHostBuilderExtensions << (S,#DDAA00) static >>
        }

        namespace Mvc {
            enum CompatibilityVersion
            class ApiControllerAttribute
            class RouteAttribute
        }

        namespace Builder {
            interface IApplicationBuilder
            class MvcApplicationBuilderExtensions << (S,#DDAA00) static >>
            class HealthCheckApplicationBuilderExtensions << (S,#DDAA00) static >>
        }
    }

    namespace ServiceFabric {
        namespace Services {
            namespace Runtime {
                abstract StatelessService
                class ServiceRuntime << (S,#DDAA00) static >>
            }

            namespace Communication {
                namespace Runtime {
                    class ServiceInstanceListener
                }

                namespace AspNetCore {
                    class KestrelCommunicationListener
                    class WebHostBuilderServiceFabricExtension << (S,#DDAA00) static >>
                    enum ServiceFabricIntegrationOptions
                }
            }
        }
    }
}

'layout Microsoft namespaces'
Microsoft.Extensions -[hidden]----> Microsoft.AspNetCore
Microsoft.AspNetCore -[hidden]---> Microsoft.ServiceFabric

'layout Microsoft.Extensions namespaces'
Microsoft.Extensions.Configuration -[hidden]-> Microsoft.Extensions.DependencyInjection
'Microsoft.Extensions.DependencyInjection -[hidden]--> Microsoft.Extensions.Primitives'

Microsoft.Extensions.DependencyInjection.HealthCheckServiceCollectionExtensions -[hidden]-> Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions

Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions -[hidden]> Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions


'layout Microsoft.AspNetCore namespaces'
Microsoft.AspNetCore.Builder -[hidden]-> Microsoft.AspNetCore.Hosting
Microsoft.AspNetCore.Hosting -[hidden]-> Microsoft.AspNetCore.Mvc

'layout Microsoft.ServiceFabric namespaces'
Microsoft.ServiceFabric.Services.Communication.Runtime -[hidden]-> Microsoft.ServiceFabric.Services.Communication.AspNetCore
Microsoft.ServiceFabric.Services.Communication.AspNetCore -[hidden]-> Microsoft.ServiceFabric.Services.Runtime

namespace System.Net.Http #whitesmoke {
    interface IHttpClientFactory
}

'layout Serilog namespaces'
Serilog.Log -[hidden]--> Serilog.Context
Serilog.Context -[hidden]> Serilog.Configuration
Serilog.Configuration -[hidden]> Serilog.Core

'Emulation Service Connections'
EmulationService.Controllers.EmulationController o--> Microsoft.AspNetCore.Mvc.ApiControllerAttribute
EmulationService.Controllers.EmulationController o--> Microsoft.AspNetCore.Mvc.RouteAttribute
EmulationService.Controllers.EmulationController -up-|> ClusterEmulator.Emulation.Controllers.AdaptableController

EmulationService.Telemetry.CorrelatedLogContext .up.|> ClusterEmulator.Emulation.Logging.IScopedLogContextFactory
EmulationService.Telemetry.CorrelatedLogContext --> Microsoft.Extensions.Primitives.StringValues
EmulationService.Telemetry.CorrelatedLogContext -up---> Serilog.Context.LogContext

EmulationService.EmulationService --|> Microsoft.ServiceFabric.Services.Runtime.StatelessService
EmulationService.EmulationService o-up---> Serilog.ILogger
EmulationService.EmulationService -up-> ClusterEmulator.ServiceFabric.Telemetry.StatelessServiceEnricher
EmulationService.EmulationService -up-> System.Fabric.StatelessServiceContext
EmulationService.EmulationService --> Microsoft.ServiceFabric.Services.Communication.Runtime.ServiceInstanceListener
EmulationService.EmulationService --> Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener
EmulationService.EmulationService --> Microsoft.ServiceFabric.Services.Communication.AspNetCore.ServiceFabricIntegrationOptions
EmulationService.EmulationService --> Microsoft.ServiceFabric.Services.Communication.AspNetCore.WebHostBuilderServiceFabricExtension
EmulationService.EmulationService --> Microsoft.AspNetCore.Hosting.WebHostBuilder
EmulationService.EmulationService --> Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions
EmulationService.EmulationService --> Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions
EmulationService.EmulationService --> Microsoft.AspNetCore.Hosting.HostingAbstractionsWebHostBuilderExtensions
EmulationService.EmulationService --> Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions
EmulationService.EmulationService --> Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions
EmulationService.EmulationService -up-> ClusterEmulator.ServiceFabric.Extensions.ServiceCollectionExtensions
EmulationService.EmulationService --> ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions
EmulationService.EmulationService -up---> Serilog.SerilogWebHostBuilderExtensions

EmulationService.Program o--> Microsoft.Extensions.Configuration.IConfiguration
EmulationService.Program --> Microsoft.Extensions.Configuration.ConfigurationBuilder
EmulationService.Program --> Microsoft.Extensions.Configuration.FileConfigurationExtensions
EmulationService.Program --> Microsoft.Extensions.Configuration.JsonConfigurationExtensions
EmulationService.Program --> Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions
EmulationService.Program --> Microsoft.ServiceFabric.Services.Runtime.ServiceRuntime
EmulationService.Program -up---> Serilog.Log
EmulationService.Program -up---> Serilog.LoggerConfiguration
EmulationService.Program -up---> Serilog.Core.Logger
EmulationService.Program -up---> Serilog.Configuration.LoggerSettingsConfiguration
EmulationService.Program -up---> Serilog.ConfigurationLoggerConfigurationExtensions

EmulationService.Startup o-up-> ClusterEmulator.Emulation.Core.IRegistry
EmulationService.Startup -up-> ClusterEmulator.Emulation.Core.IEngine
EmulationService.Startup --> Microsoft.Extensions.DependencyInjection.IServiceCollection
EmulationService.Startup --> Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions
EmulationService.Startup --> Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions
EmulationService.Startup --> Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions
EmulationService.Startup --> Microsoft.Extensions.DependencyInjection.HealthCheckServiceCollectionExtensions
EmulationService.Startup --> Microsoft.AspNetCore.Mvc.CompatibilityVersion
EmulationService.Startup --> Microsoft.AspNetCore.Builder.IApplicationBuilder
EmulationService.Startup --> Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions
EmulationService.Startup --> Microsoft.AspNetCore.Builder.HealthCheckApplicationBuilderExtensions
EmulationService.Startup -up--> System.Net.Http.IHttpClientFactory
EmulationService.Startup -up-> ClusterEmulator.Emulation.Extensions.ServiceCollectionExtensions
EmulationService.Startup -up-> ClusterEmulator.Emulation.Logging.IScopedLogContextFactory

@enduml