@startuml

'Import skinparams'
!include .\Skinparams.puml

title ClusterEmulator.ApplicationInsights Class Diagram

namespace ClusterEmulator.ApplicationInsights.Telemetry {
    class AppInsightsTelemetryConverter extends Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter {
        + Convert(logEvent, formatProvider) : IEnumerable<ITelemetry>
        - TryGetScalarProperty(logEvent, propertyName, out scalarValue) : boolean
    }

    class LoggerExtensions << (S,#DDAA00) static >> {
        {static} + WithOperationId(loggerEnrichmentConfiguration) : LoggerConfiguration
    }

    class OperationIdEnricher {
        + Enrich(logEvent, logEventPropertyFactory)
    }

    class PropertyNames {
        + OperationId : string
        + RequestId : string
    }

    LoggerExtensions -right-> OperationIdEnricher
    OperationIdEnricher -right-> PropertyNames
}

namespace Microsoft.ApplicationInsights.Channel #whitesmoke {
    interface ITelemetry
}

namespace Serilog #whitesmoke {
    class LoggerConfiguration

    namespace Core #whitesmoke {
        interface ILogEventEnricher
        interface ILogEventPropertyFactory
    }

    namespace Configuration #whitesmoke {
        class LoggerEnrichmentConfiguration
    }

    namespace Events #whitesmoke {
        class LogEvent
        class ScalarValue
        class LogEventProperty
    }
}

namespace Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters #whitesmoke {
    class TraceTelemetryConverter
}

ClusterEmulator.ApplicationInsights.Telemetry.AppInsightsTelemetryConverter --> Microsoft.ApplicationInsights.Channel.ITelemetry
ClusterEmulator.ApplicationInsights.Telemetry.AppInsightsTelemetryConverter --> Serilog.Events.LogEvent
ClusterEmulator.ApplicationInsights.Telemetry.AppInsightsTelemetryConverter --> Serilog.Events.ScalarValue

ClusterEmulator.ApplicationInsights.Telemetry.LoggerExtensions --> Serilog.LoggerConfiguration
ClusterEmulator.ApplicationInsights.Telemetry.LoggerExtensions --> Serilog.Configuration.LoggerEnrichmentConfiguration

ClusterEmulator.ApplicationInsights.Telemetry.OperationIdEnricher --> Serilog.Core.ILogEventPropertyFactory
ClusterEmulator.ApplicationInsights.Telemetry.OperationIdEnricher ..|> Serilog.Core.ILogEventEnricher
ClusterEmulator.ApplicationInsights.Telemetry.OperationIdEnricher --> Serilog.Events.LogEvent
ClusterEmulator.ApplicationInsights.Telemetry.OperationIdEnricher --> Serilog.Events.LogEventProperty
ClusterEmulator.ApplicationInsights.Telemetry.OperationIdEnricher --> Serilog.Events.ScalarValue

@enduml