@startuml

skinparam component {
  FontName Arial
  BorderColor black
  BackgroundColor gold
  ArrowColor #DD3333
}

title Cluster Emulator Components

package "Project Specific" {
  [ClusterEmulator.ApplicationInsights]
  [ClusterEmulator.ServiceFabric]
  [Emulation Service]

  frame "Serilog" {
    [Serilog.AspNetCore] #WhiteSmoke
    [Serilog.Settings.Configuration] #WhiteSmoke
    [Serilog.Sinks.ApplicationInsights] #WhiteSmoke
  }

  frame "Service Fabric" {
    [Microsoft.ServiceFabric] #WhiteSmoke
    [Microsoft.ServiceFabric.AspNetCore.Kestrel] #WhiteSmoke
  }
}

package "Fully Portable" {
  [ClusterEmulator.Emulation]
  [ClusterEmulator.Models]

  frame ".NET Core" {
    [Microsoft.AspNetCore.App] #WhiteSmoke
    [Microsoft.Extensions.Logging] #WhiteSmoke
  }

  frame "Newtonsoft" {
    [Newtonsoft.Json] #WhiteSmoke
  }

  frame "Polly Packages" {
    [Microsoft.Extensions.Http.Polly] #WhiteSmoke
    [Polly] #WhiteSmoke
    [Polly.Caching.Memory] #WhiteSmoke
  }
}

[Emulation Service] --> [ClusterEmulator.ApplicationInsights]
[Emulation Service] -up-> [ClusterEmulator.Emulation]
[Emulation Service] --> [ClusterEmulator.ServiceFabric]
[Emulation Service] -up-> [Microsoft.AspNetCore.App]
[Emulation Service] -up-> [Microsoft.Extensions.Logging]
[Emulation Service] --> [Microsoft.ServiceFabric.AspNetCore.Kestrel]
[Emulation Service] --> [Serilog.Settings.Configuration]
[Emulation Service] --> [Serilog.Sinks.ApplicationInsights]

[ClusterEmulator.ApplicationInsights] -up-> [Microsoft.AspNetCore.App]
[ClusterEmulator.ApplicationInsights] --> [Serilog.Sinks.ApplicationInsights]

[ClusterEmulator.Emulation] -up-> [ClusterEmulator.Models]
[ClusterEmulator.Emulation] --> [Microsoft.AspNetCore.App]
[ClusterEmulator.Emulation] -up-> [Microsoft.Extensions.Http.Polly]
[ClusterEmulator.Emulation] --> [Microsoft.Extensions.Logging]
[ClusterEmulator.Emulation] -up-> [Newtonsoft.Json]
[ClusterEmulator.Emulation] -up-> [Polly]
[ClusterEmulator.Emulation] -up-> [Polly.Caching.Memory]

[ClusterEmulator.Models] -up-> [Newtonsoft.Json]

[ClusterEmulator.ServiceFabric] -up-> [Microsoft.AspNetCore.App]
[ClusterEmulator.ServiceFabric] --> [Microsoft.ServiceFabric]
[ClusterEmulator.ServiceFabric] --> [Serilog.AspNetCore]

@enduml