@startuml

'Import Azure Sympols (MIT License)'
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist
!include AzurePuml/AzureCommon.puml
!include AzurePuml/Compute/AzureServiceFabric.puml
!include AzurePuml/Compute/AzureVirtualMachineScaleSet.puml
!include AzurePuml/DevOps/AzureApplicationInsights.puml
!include AzurePuml/Management/AzureLogAnalytics.puml
!include AzurePuml/Networking/AzureLoadBalancer.puml
!include AzurePuml/Security/AzureKeyVault.puml

'Import skinparams'
!include .\Skinparams.puml

skinparam frame {
  Shadowing false
}

title eCommerce Infrastructure

interface request

cloud az as "Azure" {
  request -[hidden]> az

  AzureLoadBalancer(loadBalancer, "Load Balancer", "ingress controller", "Handles service ingress with liveness tests")
  
  frame "Secure Virtual Network" {
    AzureServiceFabric(sfCluster, "Service Fabric Cluster", "3 Node cluster")
    AzureVirtualMachineScaleSet(scaleSet, "VM Scale Set", "3 VMs", "Service hosting")

    sfCluster -> scaleSet
  }

  loadBalancer -> sfCluster

  AzureKeyVault(keyVault, "Key Vault", "secret storage")
  database "Platform\nTelemetry\nStorage" as storage
  sfCluster --> keyVault
  sfCluster --> storage
  
  AzureLogAnalytics(logAnalytics, "Log Analytics", "Platform and node telemetry")


  AzureApplicationInsights(appInsights, "Application Insights", "Application telemetry")
  scaleSet --> appInsights  
  scaleSet --> logAnalytics
  storage -> logAnalytics
}

request -> loadBalancer

@enduml
