@startuml

title Application Generation and Deployment


skinparam component {
  FontName Arial
  BorderColor black
  BackgroundColor whitesmoke
  ArrowColor black
}

skinparam interface {
  BorderColor black
  BackgroundColor whitesmoke
}

skinparam file {
  BorderColor black
  BackgroundColor whitesmoke
}

skinparam agent {
  BorderColor black
  BackgroundColor whitesmoke
}

interface "dotnet new" as dotnetNew
interface "Cluster\nEmulator\nLibraries" as ClusterLibraries
interface "EmulationService\nTemplate" as ServiceTemplate

folder Generated {
    file "ports.json" as ports
    file "Emulation Library Projects" as libraries
    file "Templated Service Projects" as projects
    file "Packaged Application" as appPackage
}

projects .. libraries
libraries -[hidden]-> ports

package "Application Generation" {
    agent AppGenerator

    file "appsettings.json" as appSettings
    file "App Configuration.json" as appConfig

    appConfig .. appSettings : optional reference
    appConfig -> AppGenerator

    AppGenerator .up.> dotnetNew

    AppGenerator -> projects : output
    AppGenerator -> libraries : output
    AppGenerator -> ports : output
}

ServiceTemplate --> AppGenerator
ClusterLibraries --> AppGenerator

interface "dotnet publish" as dotnetPub

package "Package Generation" {
    agent AppPacker

    ports -> AppPacker
    projects -> AppPacker

    AppPacker ..> dotnetPub
    AppPacker -> appPackage : output
}

package "Infrastructure Provisioning" {
    [Blah3]
}

package "Application Deployment" {
    [Blah4]
}

cloud {
    [Cluster]
}


@enduml
