@startuml

skinparam class {
    FontName Arial
    BorderColor black
    BackgroundColor whitesmoke
    ArrowColor black
    FontSize 18
    FontStyle bold
    AttributeFontSize 16
    StereotypeFontSize 16
}

skinparam component {
  FontName Arial
  BorderColor black
  BackgroundColor LightSkyBlue
  ArrowColor black
}

skinparam database {
  BorderColor CornflowerBlue
  BackgroundColor white
}

skinparam interface {
  BorderColor black
  BackgroundColor whitesmoke
}

skinparam actor {
  BorderColor black
  BackgroundColor whitesmoke
}

skinparam file {
  BorderColor black
  BackgroundColor whitesmoke
}

skinparam agent {
  BorderColor CornflowerBlue
  BackgroundColor LightSkyBlue
}

@enduml