@startuml

title eCommerce System

'Import skinparams'
!include .\Skinparams.puml

actor "Single Page\nApplication" as User
actor "Business\nIntelligence\nAutomation" as Auto
User -[hidden]-- Auto

cloud " " as Cluster {
    agent "Checkout API" as Checkout
    agent "Browse API" as Browse
    agent "BusinessIntelligence API" as BI

    agent "Cart" as Cart
    agent "Payments" as Payments
    agent "Accounts" as Accounts

    agent "Catalogue" as Catalogue
    agent "Search" as Search
}

'Set client positions'
User -right-> Checkout : Get Items,\nAdd Item,\nRemove Item,\nMake Payment
User -right-> Browse : Login,\nGet Products,\nSearch
Auto -right-> BI : Get Data

'Create internal columns'
Checkout -[hidden]- Browse
Browse -[hidden]- BI

Cart -[hidden]- Payments
Payments -[hidden]- Accounts

Catalogue -[hidden]- Search

Checkout -> Cart : Get Items,\nAdd Item,\nRemove Item
Checkout --> Payments : Process Payment

Cart -> Catalogue : Get Product

Browse -> Accounts : Get Account Id
Browse -right-> Search : Get Batch,\nQuery

BI -up-> Accounts : Get Purchases
BI -up-> Catalogue : Get Products

Payments -up-> Cart : Get Items,\nEmpty Cart
Payments --> Accounts : Get Payment Info,\nUpdate Purchases
Payments -> Catalogue : Get Products,\nUpdate Product

Search -up--> Catalogue : Get Products

@enduml